name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Lint
        run: |
          npm install
          npm run lint
          npm run build

      - name: Deploy to VPS
        if: success() # Only run if previous steps succeeded
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /root/meetstr
            git pull origin main
            npm install
            npm run build
            pm2 restart meetstr
            pm2 save
